-- ==============================================
-- BTC核心数据库 - 职位-角色映射数据（第1部分）
-- ==============================================

USE btc_core;

-- 插入职位-角色映射数据（职位与权限角色的解耦）
INSERT INTO sys_position_role (position_id, role_id, is_default, created_by) VALUES
-- 总经理职位映射
('POS_INERT_CEO', 'ROLE_DATA_VIEWER_ALL', TRUE, 'SYSTEM'),
('POS_INERT_CEO', 'ROLE_BI_ANALYST', TRUE, 'SYSTEM'),
('POS_INERT_CEO', 'ROLE_PRODUCTION_PLAN_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_CEO', 'ROLE_PROCUREMENT_ORDER_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_CEO', 'ROLE_FINANCE_APPROVE', TRUE, 'SYSTEM'),

-- 物流经理职位映射
('POS_INERT_LOGISTICS_MGR', 'ROLE_WAREHOUSE_RECEIVE', TRUE, 'SYSTEM'),
('POS_INERT_LOGISTICS_MGR', 'ROLE_WAREHOUSE_ISSUE', TRUE, 'SYSTEM'),
('POS_INERT_LOGISTICS_MGR', 'ROLE_INVENTORY_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_LOGISTICS_MGR', 'ROLE_CUSTOMS_DECLARE', TRUE, 'SYSTEM'),
('POS_INERT_LOGISTICS_MGR', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 海关专员职位映射
('POS_INERT_CUSTOMS', 'ROLE_CUSTOMS_DECLARE', TRUE, 'SYSTEM'),
('POS_INERT_CUSTOMS', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 仓管大组长职位映射
('POS_INERT_WAREHOUSE_LEADER', 'ROLE_WAREHOUSE_RECEIVE', TRUE, 'SYSTEM'),
('POS_INERT_WAREHOUSE_LEADER', 'ROLE_WAREHOUSE_ISSUE', TRUE, 'SYSTEM'),
('POS_INERT_WAREHOUSE_LEADER', 'ROLE_INVENTORY_COUNT', TRUE, 'SYSTEM'),
('POS_INERT_WAREHOUSE_LEADER', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 采购经理职位映射
('POS_INERT_PROCUREMENT_MGR', 'ROLE_PROCUREMENT_ORDER_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT_MGR', 'ROLE_PROCUREMENT_ORDER_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT_MGR', 'ROLE_SUPPLIER_MANAGE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT_MGR', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 采购ECN专员职位映射
('POS_INERT_PROCUREMENT_ECN', 'ROLE_PROCUREMENT_ECN_MANAGE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT_ECN', 'ROLE_PROCUREMENT_ORDER_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT_ECN', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 采购专员职位映射
('POS_INERT_PROCUREMENT', 'ROLE_PROCUREMENT_ORDER_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 采购辅料专员职位映射
('POS_INERT_PROCUREMENT_AUXMAT', 'ROLE_PROCUREMENT_ORDER_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT_AUXMAT', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 采购包材专员职位映射
('POS_INERT_PROCUREMENT_PKG', 'ROLE_PROCUREMENT_ORDER_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PROCUREMENT_PKG', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 财务经理职位映射
('POS_INERT_FINANCE_MGR', 'ROLE_FINANCE_VIEW', TRUE, 'SYSTEM'),
('POS_INERT_FINANCE_MGR', 'ROLE_FINANCE_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_FINANCE_MGR', 'ROLE_PROCUREMENT_ORDER_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_FINANCE_MGR', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 财务主管职位映射
('POS_INERT_FINANCE_SUPER', 'ROLE_FINANCE_VIEW', TRUE, 'SYSTEM'),
('POS_INERT_FINANCE_SUPER', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 财务专员职位映射
('POS_INERT_FINANCE', 'ROLE_FINANCE_VIEW', TRUE, 'SYSTEM'),

-- 人事主管职位映射
('POS_INERT_HR_SUPER', 'ROLE_HR_MANAGE', TRUE, 'SYSTEM'),
('POS_INERT_HR_SUPER', 'ROLE_USER_MANAGE', TRUE, 'SYSTEM'),
('POS_INERT_HR_SUPER', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 人事专员职位映射
('POS_INERT_HR', 'ROLE_HR_MANAGE', TRUE, 'SYSTEM'),

-- 生产经理职位映射
('POS_INERT_PRODUCTION_MGR', 'ROLE_PRODUCTION_PLAN_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_MGR', 'ROLE_PRODUCTION_PLAN_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_MGR', 'ROLE_WORK_ORDER_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_MGR', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 生产出货主管职位映射
('POS_INERT_PRODUCTION_SHIP', 'ROLE_PRODUCTION_PACK', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_SHIP', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 生产车间主管职位映射
('POS_INERT_PRODUCTION_WORKSHOP', 'ROLE_WORK_ORDER_EXECUTE', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_WORKSHOP', 'ROLE_WORK_ORDER_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_WORKSHOP', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 生产大组长职位映射
('POS_INERT_PRODUCTION_LEADER', 'ROLE_WORK_ORDER_EXECUTE', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_LEADER', 'ROLE_PRODUCTION_TEST', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_LEADER', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 生产组长职位映射
