-- ==============================================
-- BTC核心数据库 - 职位数据
-- ==============================================

USE btc_core;

-- 插入职位数据（基于user_profile真实职位）
INSERT INTO sys_position (position_id, tenant_id, position_code, position_name, dept_id, position_level, created_by) VALUES
-- INERT内网职位
('POS_INERT_CEO', 'TENANT_INERT', 'CEO', '总经理', 'DEPT_INERT_MANAGEMENT', 1, 'SYSTEM'),
('POS_INERT_LOGISTICS_MGR', 'TENANT_INERT', 'LOGISTICS_MGR', '物流经理', 'DEPT_INERT_LOGISTICS', 2, 'SYSTEM'),
('POS_INERT_CUSTOMS', 'TENANT_INERT', 'CUSTOMS', '海关专员', 'DEPT_INERT_LOGISTICS', 4, 'SYSTEM'),
('POS_INERT_WAREHOUSE_LEADER', 'TENANT_INERT', 'WAREHOUSE_LEADER', '仓管大组长', 'DEPT_INERT_LOGISTICS', 3, 'SYSTEM'),
('POS_INERT_PROCUREMENT_MGR', 'TENANT_INERT', 'PROCUREMENT_MGR', '采购经理', 'DEPT_INERT_PROCUREMENT', 2, 'SYSTEM'),
('POS_INERT_PROCUREMENT_ECN', 'TENANT_INERT', 'PROCUREMENT_ECN', '采购ECN变更专员', 'DEPT_INERT_PROCUREMENT', 4, 'SYSTEM'),
('POS_INERT_PROCUREMENT', 'TENANT_INERT', 'PROCUREMENT', '采购专员', 'DEPT_INERT_PROCUREMENT', 4, 'SYSTEM'),
('POS_INERT_PROCUREMENT_AUXMAT', 'TENANT_INERT', 'PROCUREMENT_AUXMAT', '采购辅料专员', 'DEPT_INERT_PROCUREMENT', 4, 'SYSTEM'),
('POS_INERT_PROCUREMENT_PKG', 'TENANT_INERT', 'PROCUREMENT_PKG', '采购包材专员', 'DEPT_INERT_PROCUREMENT', 4, 'SYSTEM'),
('POS_INERT_FINANCE_MGR', 'TENANT_INERT', 'FINANCE_MGR', '财务经理', 'DEPT_INERT_FINANCE', 2, 'SYSTEM'),
('POS_INERT_FINANCE_SUPER', 'TENANT_INERT', 'FINANCE_SUPER', '财务主管', 'DEPT_INERT_FINANCE', 3, 'SYSTEM'),
('POS_INERT_FINANCE', 'TENANT_INERT', 'FINANCE', '财务专员', 'DEPT_INERT_FINANCE', 4, 'SYSTEM'),
('POS_INERT_HR_SUPER', 'TENANT_INERT', 'HR_SUPER', '人事主管', 'DEPT_INERT_HR', 3, 'SYSTEM'),
('POS_INERT_HR', 'TENANT_INERT', 'HR', '人事专员', 'DEPT_INERT_HR', 4, 'SYSTEM'),
('POS_INERT_PRODUCTION_MGR', 'TENANT_INERT', 'PRODUCTION_MGR', '生产经理', 'DEPT_INERT_PRODUCTION', 2, 'SYSTEM'),
('POS_INERT_PRODUCTION_SHIP', 'TENANT_INERT', 'PRODUCTION_SHIP', '生产出货主管', 'DEPT_INERT_PRODUCTION', 3, 'SYSTEM'),
('POS_INERT_PRODUCTION_WORKSHOP', 'TENANT_INERT', 'PRODUCTION_WORKSHOP', '生产车间主管', 'DEPT_INERT_PRODUCTION', 3, 'SYSTEM'),
('POS_INERT_PRODUCTION_LEADER', 'TENANT_INERT', 'PRODUCTION_LEADER', '生产大组长', 'DEPT_INERT_PRODUCTION', 4, 'SYSTEM'),
('POS_INERT_PRODUCTION_GROUP', 'TENANT_INERT', 'PRODUCTION_GROUP', '生产组长', 'DEPT_INERT_PRODUCTION', 5, 'SYSTEM'),
('POS_INERT_PRODUCTION_ENG', 'TENANT_INERT', 'PRODUCTION_ENG', '生产工程师', 'DEPT_INERT_PRODUCTION', 4, 'SYSTEM'),
('POS_INERT_PRODUCTION_AUTO', 'TENANT_INERT', 'PRODUCTION_AUTO', '生产自动化工程师', 'DEPT_INERT_PRODUCTION', 4, 'SYSTEM'),
('POS_INERT_PRODUCTION_CLERK', 'TENANT_INERT', 'PRODUCTION_CLERK', '生产文员', 'DEPT_INERT_PRODUCTION', 5, 'SYSTEM'),
('POS_INERT_ENGINEERING_MGR', 'TENANT_INERT', 'ENGINEERING_MGR', '工程经理', 'DEPT_INERT_ENGINEERING', 2, 'SYSTEM'),
('POS_INERT_ENGINEERING_SUPER', 'TENANT_INERT', 'ENGINEERING_SUPER', '工程主管', 'DEPT_INERT_ENGINEERING', 3, 'SYSTEM'),
('POS_INERT_NPD_ENG', 'TENANT_INERT', 'NPD_ENG', 'NPD工程师', 'DEPT_INERT_ENGINEERING', 4, 'SYSTEM'),
('POS_INERT_MOLD_ENG', 'TENANT_INERT', 'MOLD_ENG', '模具工程师', 'DEPT_INERT_ENGINEERING', 4, 'SYSTEM'),
('POS_INERT_PROCESS_ENG', 'TENANT_INERT', 'PROCESS_ENG', '生产工程师', 'DEPT_INERT_ENGINEERING', 4, 'SYSTEM'),
('POS_INERT_QUALITY_MGR', 'TENANT_INERT', 'QUALITY_MGR', '品质经理', 'DEPT_INERT_QUALITY', 2, 'SYSTEM'),
('POS_INERT_QUALITY_SUPER', 'TENANT_INERT', 'QUALITY_SUPER', '品质主管', 'DEPT_INERT_QUALITY', 3, 'SYSTEM'),
('POS_INERT_FAI', 'TENANT_INERT', 'FAI', '首件核对专员', 'DEPT_INERT_QUALITY', 4, 'SYSTEM'),
('POS_INERT_IQC', 'TENANT_INERT', 'IQC', 'IQC专员', 'DEPT_INERT_QUALITY', 4, 'SYSTEM'),
('POS_INERT_IPQC', 'TENANT_INERT', 'IPQC', 'IPQC专员', 'DEPT_INERT_QUALITY', 4, 'SYSTEM'),
('POS_INERT_QUALITY_EXTERNAL', 'TENANT_INERT', 'QUALITY_EXTERNAL', '品质外派专员', 'DEPT_INERT_QUALITY', 4, 'SYSTEM'),
('POS_INERT_QUALITY_REPAIR', 'TENANT_INERT', 'QUALITY_REPAIR', '品质维修专员', 'DEPT_INERT_QUALITY', 4, 'SYSTEM'),
('POS_INERT_QUALITY_CLERK', 'TENANT_INERT', 'QUALITY_CLERK', '品质文员', 'DEPT_INERT_QUALITY', 5, 'SYSTEM'),
('POS_INERT_MAINTENANCE', 'TENANT_INERT', 'MAINTENANCE', '维修主管', 'DEPT_INERT_MAINTENANCE', 3, 'SYSTEM'),
('POS_INERT_IT_ENG', 'TENANT_INERT', 'IT_ENG', 'IT工程师', 'DEPT_INERT_IT', 4, 'SYSTEM'),
('POS_INERT_IT_DEV', 'TENANT_INERT', 'IT_DEV', 'IT开发', 'DEPT_INERT_IT', 4, 'SYSTEM'),
('POS_INERT_IT_OPS', 'TENANT_INERT', 'IT_OPS', 'IT运维专员', 'DEPT_INERT_IT', 4, 'SYSTEM'),

-- UK_HEAD职位
('POS_UK_READONLY', 'TENANT_UK_HEAD', 'READONLY', '只读用户', 'DEPT_UK_HEAD', 4, 'SYSTEM'),

-- SUPPLIER职位
('POS_SUPPLIER_MATERIAL', 'TENANT_SUPPLIER', 'SUPPLIER_MATERIAL', '原材料供应商', 'DEPT_SUPPLIER_RAW', 4, 'SYSTEM');
