-- ==============================================
-- BTC核心数据库 - 职位-角色映射数据（第2部分）
-- ==============================================

USE btc_core;

INSERT INTO sys_position_role (position_id, role_id, is_default, created_by) VALUES
('POS_INERT_PRODUCTION_GROUP', 'ROLE_WORK_ORDER_EXECUTE', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_GROUP', 'ROLE_PRODUCTION_TEST', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_GROUP', 'ROLE_PRODUCTION_REPAIR', TRUE, 'SYSTEM'),

-- 生产工程师职位映射
('POS_INERT_PRODUCTION_ENG', 'ROLE_ENGINEERING_PROCESS', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_ENG', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 生产自动化工程师职位映射
('POS_INERT_PRODUCTION_AUTO', 'ROLE_ENGINEERING_PROCESS', TRUE, 'SYSTEM'),
('POS_INERT_PRODUCTION_AUTO', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 生产文员职位映射
('POS_INERT_PRODUCTION_CLERK', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 工程经理职位映射
('POS_INERT_ENGINEERING_MGR', 'ROLE_ENGINEERING_NPD', TRUE, 'SYSTEM'),
('POS_INERT_ENGINEERING_MGR', 'ROLE_ENGINEERING_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_ENGINEERING_MGR', 'ROLE_PRODUCTION_PLAN_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_ENGINEERING_MGR', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 工程主管职位映射
('POS_INERT_ENGINEERING_SUPER', 'ROLE_ENGINEERING_NPD', TRUE, 'SYSTEM'),
('POS_INERT_ENGINEERING_SUPER', 'ROLE_ENGINEERING_PROCESS', TRUE, 'SYSTEM'),
('POS_INERT_ENGINEERING_SUPER', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- NPD工程师职位映射
('POS_INERT_NPD_ENG', 'ROLE_ENGINEERING_NPD', TRUE, 'SYSTEM'),
('POS_INERT_NPD_ENG', 'ROLE_FAI_VERIFY', TRUE, 'SYSTEM'),
('POS_INERT_NPD_ENG', 'ROLE_ENGINEERING_PROCESS', TRUE, 'SYSTEM'),
('POS_INERT_NPD_ENG', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 模具工程师职位映射
('POS_INERT_MOLD_ENG', 'ROLE_ENGINEERING_MOLD', TRUE, 'SYSTEM'),
('POS_INERT_MOLD_ENG', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 生产工程师职位映射
('POS_INERT_PROCESS_ENG', 'ROLE_ENGINEERING_PROCESS', TRUE, 'SYSTEM'),
('POS_INERT_PROCESS_ENG', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 品质经理职位映射
('POS_INERT_QUALITY_MGR', 'ROLE_QUALITY_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_MGR', 'ROLE_IQC_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_MGR', 'ROLE_TRACE_ANALYST', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_MGR', 'ROLE_QUALITY_NCR_HANDLE', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_MGR', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 品质主管职位映射
('POS_INERT_QUALITY_SUPER', 'ROLE_IQC_APPROVE', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_SUPER', 'ROLE_QUALITY_NCR_HANDLE', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_SUPER', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- FAI专员职位映射
('POS_INERT_FAI', 'ROLE_FAI_VERIFY', TRUE, 'SYSTEM'),
('POS_INERT_FAI', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- IQC专员职位映射
('POS_INERT_IQC', 'ROLE_IQC_INSPECT', TRUE, 'SYSTEM'),
('POS_INERT_IQC', 'ROLE_QUALITY_NCR_CREATE', TRUE, 'SYSTEM'),
('POS_INERT_IQC', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- IPQC专员职位映射
('POS_INERT_IPQC', 'ROLE_IPQC_INSPECT', TRUE, 'SYSTEM'),
('POS_INERT_IPQC', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 品质外派专员职位映射
('POS_INERT_QUALITY_EXTERNAL', 'ROLE_IQC_INSPECT', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_EXTERNAL', 'ROLE_SUPPLIER_MANAGE', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_EXTERNAL', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 品质维修专员职位映射
('POS_INERT_QUALITY_REPAIR', 'ROLE_PRODUCTION_REPAIR', TRUE, 'SYSTEM'),
('POS_INERT_QUALITY_REPAIR', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 品质文员职位映射
('POS_INERT_QUALITY_CLERK', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- 维修主管职位映射
('POS_INERT_MAINTENANCE', 'ROLE_PRODUCTION_REPAIR', TRUE, 'SYSTEM'),
('POS_INERT_MAINTENANCE', 'ROLE_DATA_VIEWER_DEPT', TRUE, 'SYSTEM'),

-- IT工程师职位映射
('POS_INERT_IT_ENG', 'ROLE_SYSTEM_ADMIN', TRUE, 'SYSTEM'),
('POS_INERT_IT_ENG', 'ROLE_USER_MANAGE', TRUE, 'SYSTEM'),

-- IT开发职位映射
('POS_INERT_IT_DEV', 'ROLE_SYSTEM_ADMIN', TRUE, 'SYSTEM'),
('POS_INERT_IT_DEV', 'ROLE_MODULE_ADMIN', TRUE, 'SYSTEM'),

-- IT运维专员职位映射
('POS_INERT_IT_OPS', 'ROLE_SYSTEM_ADMIN', TRUE, 'SYSTEM'),

-- 英国只读用户职位映射
('POS_UK_READONLY', 'ROLE_DATA_VIEWER_ALL', TRUE, 'SYSTEM'),
('POS_UK_READONLY', 'ROLE_BI_ANALYST', TRUE, 'SYSTEM'),

-- 供应商职位映射
('POS_SUPPLIER_MATERIAL', 'ROLE_SUPPLIER_ORDER_VIEW', TRUE, 'SYSTEM'),
('POS_SUPPLIER_MATERIAL', 'ROLE_SUPPLIER_IQC_COLLABORATE', TRUE, 'SYSTEM'),
('POS_SUPPLIER_MATERIAL', 'ROLE_SUPPLIER_DELIVERY_MANAGE', TRUE, 'SYSTEM');

-- 插入基于流程树的权限数据
INSERT 