-- ==============================================
-- BTC核心数据库 - 角色数据
-- ==============================================

USE btc_core;

-- 插入基于业务行为的RBAC角色数据
INSERT INTO sys_role (role_id, tenant_id, parent_role_id, role_code, role_name, role_type, role_level, data_scope, inherit_permissions, inherit_data_scope, created_by) VALUES
-- ===== 通用角色（跨租户） =====

-- 1. 数据查看类角色
('ROLE_DATA_VIEWER_ALL', 'TENANT_INERT', NULL, 'DATA_VIEWER_ALL', '全局数据查看', 'NORMAL', 1, 'ALL', FALSE, FALSE, 'SYSTEM'),
('ROLE_DATA_VIEWER_DEPT', 'TENANT_INERT', 'ROLE_DATA_VIEWER_ALL', 'DATA_VIEWER_DEPT', '部门数据查看', 'NORMAL', 2, 'DEPT', TRUE, FALSE, 'SYSTEM'),
('ROLE_BI_ANALYST', 'TENANT_INERT', 'ROLE_DATA_VIEWER_ALL', 'BI_ANALYST', 'BI数据分析', 'NORMAL', 2, 'ALL', TRUE, TRUE, 'SYSTEM'),

-- 2. 采购域角色
('ROLE_PROCUREMENT_ORDER_CREATE', 'TENANT_INERT', NULL, 'PROCUREMENT_ORDER_CREATE', '创建采购订单', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_PROCUREMENT_ORDER_APPROVE', 'TENANT_INERT', 'ROLE_PROCUREMENT_ORDER_CREATE', 'PROCUREMENT_ORDER_APPROVE', '审批采购订单', 'NORMAL', 2, 'DEPT_AND_CHILD', TRUE, TRUE, 'SYSTEM'),
('ROLE_PROCUREMENT_ECN_MANAGE', 'TENANT_INERT', NULL, 'PROCUREMENT_ECN_MANAGE', 'ECN变更管理', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_SUPPLIER_MANAGE', 'TENANT_INERT', NULL, 'SUPPLIER_MANAGE', '供应商管理', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),

-- 3. 物流域角色
('ROLE_CUSTOMS_DECLARE', 'TENANT_INERT', NULL, 'CUSTOMS_DECLARE', '海关报备', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_WAREHOUSE_RECEIVE', 'TENANT_INERT', NULL, 'WAREHOUSE_RECEIVE', '收货入库', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_WAREHOUSE_ISSUE', 'TENANT_INERT', NULL, 'WAREHOUSE_ISSUE', '备料出库', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_INVENTORY_COUNT', 'TENANT_INERT', NULL, 'INVENTORY_COUNT', '库存盘点', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_INVENTORY_APPROVE', 'TENANT_INERT', 'ROLE_INVENTORY_COUNT', 'INVENTORY_APPROVE', '库存审批', 'NORMAL', 2, 'DEPT_AND_CHILD', TRUE, TRUE, 'SYSTEM'),

-- 4. 品质域角色
('ROLE_IQC_INSPECT', 'TENANT_INERT', NULL, 'IQC_INSPECT', 'IQC进料检验', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_IQC_APPROVE', 'TENANT_INERT', 'ROLE_IQC_INSPECT', 'IQC_APPROVE', 'IQC结果审批', 'NORMAL', 2, 'DEPT_AND_CHILD', TRUE, TRUE, 'SYSTEM'),
('ROLE_IPQC_INSPECT', 'TENANT_INERT', NULL, 'IPQC_INSPECT', 'IPQC过程巡检', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_OQC_INSPECT', 'TENANT_INERT', NULL, 'OQC_INSPECT', 'OQC出货检验', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_FAI_VERIFY', 'TENANT_INERT', NULL, 'FAI_VERIFY', '首件验证', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_QUALITY_NCR_CREATE', 'TENANT_INERT', NULL, 'QUALITY_NCR_CREATE', '创建NCR/SCAR', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_QUALITY_NCR_HANDLE', 'TENANT_INERT', 'ROLE_QUALITY_NCR_CREATE', 'QUALITY_NCR_HANDLE', '处理NCR/SCAR', 'NORMAL', 2, 'DEPT', TRUE, TRUE, 'SYSTEM'),
('ROLE_QUALITY_APPROVE', 'TENANT_INERT', 'ROLE_IQC_APPROVE', 'QUALITY_APPROVE', '品质审批', 'NORMAL', 3, 'DEPT_AND_CHILD', TRUE, TRUE, 'SYSTEM'),

-- 5. 生产域角色
('ROLE_PRODUCTION_PLAN_CREATE', 'TENANT_INERT', NULL, 'PRODUCTION_PLAN_CREATE', '创建生产计划', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_PRODUCTION_PLAN_APPROVE', 'TENANT_INERT', 'ROLE_PRODUCTION_PLAN_CREATE', 'PRODUCTION_PLAN_APPROVE', '审批生产计划', 'NORMAL', 2, 'DEPT_AND_CHILD', TRUE, TRUE, 'SYSTEM'),
('ROLE_WORK_ORDER_CREATE', 'TENANT_INERT', NULL, 'WORK_ORDER_CREATE', '创建工单', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_WORK_ORDER_EXECUTE', 'TENANT_INERT', NULL, 'WORK_ORDER_EXECUTE', '执行工单', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_PRODUCTION_TEST', 'TENANT_INERT', NULL, 'PRODUCTION_TEST', '生产测试', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_PRODUCTION_REPAIR', 'TENANT_INERT', NULL, 'PRODUCTION_REPAIR', '返修操作', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_PRODUCTION_PACK', 'TENANT_INERT', NULL, 'PRODUCTION_PACK', '打包出货', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),

-- 6. 工程域角色
('ROLE_ENGINEERING_NPD', 'TENANT_INERT', NULL, 'ENGINEERING_NPD', '新产品开发', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_ENGINEERING_PROCESS', 'TENANT_INERT', NULL, 'ENGINEERING_PROCESS', '工艺管理', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_ENGINEERING_MOLD', 'TENANT_INERT', NULL, 'ENGINEERING_MOLD', '模具管理', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_ENGINEERING_APPROVE', 'TENANT_INERT', 'ROLE_ENGINEERING_NPD', 'ENGINEERING_APPROVE', '工程审批', 'NORMAL', 2, 'DEPT_AND_CHILD', TRUE, TRUE, 'SYSTEM'),

-- 7. 追溯与分析角色
('ROLE_TRACE_QUERY', 'TENANT_INERT', NULL, 'TRACE_QUERY', '追溯查询', 'NORMAL', 1, 'ALL', FALSE, FALSE, 'SYSTEM'),
('ROLE_TRACE_ANALYST', 'TENANT_INERT', 'ROLE_TRACE_QUERY', 'TRACE_ANALYST', '追溯分析', 'NORMAL', 2, 'ALL', TRUE, TRUE, 'SYSTEM'),

-- 8. 系统管理角色
('ROLE_SYSTEM_ADMIN', 'TENANT_INERT', NULL, 'SYSTEM_ADMIN', '系统管理', 'SYSTEM', 1, 'ALL', FALSE, FALSE, 'SYSTEM'),
('ROLE_USER_MANAGE', 'TENANT_INERT', NULL, 'USER_MANAGE', '用户管理', 'NORMAL', 1, 'DEPT_AND_CHILD', FALSE, FALSE, 'SYSTEM'),
('ROLE_TENANT_ADMIN', 'TENANT_INERT', 'ROLE_SYSTEM_ADMIN', 'TENANT_ADMIN', '租户管理', 'SYSTEM', 2, 'ALL', TRUE, TRUE, 'SYSTEM'),
('ROLE_MODULE_ADMIN', 'TENANT_INERT', NULL, 'MODULE_ADMIN', '模块管理', 'NORMAL', 1, 'DEPT_AND_CHILD', FALSE, FALSE, 'SYSTEM'),

-- 9. 财务与HR角色
('ROLE_FINANCE_VIEW', 'TENANT_INERT', NULL, 'FINANCE_VIEW', '财务数据查看', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),
('ROLE_FINANCE_APPROVE', 'TENANT_INERT', 'ROLE_FINANCE_VIEW', 'FINANCE_APPROVE', '财务审批', 'NORMAL', 2, 'DEPT_AND_CHILD', TRUE, TRUE, 'SYSTEM'),
('ROLE_HR_MANAGE', 'TENANT_INERT', NULL, 'HR_MANAGE', '人事管理', 'NORMAL', 1, 'DEPT', FALSE, FALSE, 'SYSTEM'),

-- ===== 供应商协同角色 =====
('ROLE_SUPPLIER_ORDER_VIEW', 'TENANT_SUPPLIER', NULL, 'SUPPLIER_ORDER_VIEW', '查看采购订单', 'SUPPLIER', 1, 'SELF', FALSE, FALSE, 'SYSTEM'),
('ROLE_SUPPLIER_IQC_COLLABORATE', 'TENANT_SUPPLIER', NULL, 'SUPPLIER_IQC_COLLABORATE', 'IQC协同', 'SUPPLIER', 1, 'SELF', FALSE, FALSE, 'SYSTEM'),
('ROLE_SUPPLIER_DELIVERY_MANAGE', 'TENANT_SUPPLIER', NULL, 'SUPPLIER_DELIVERY_MANAGE', '发货管理', 'SUPPLIER', 1, 'SELF', FALSE, FALSE, 'SYSTEM'),
('ROLE_SUPPLIER_MOLD_UPDATE', 'TENANT_SUPPLIER', NULL, 'SUPPLIER_MOLD_UPDATE', '模具状态更新', 'SUPPLIER', 1, 'SELF', FALSE, FALSE, 'SYSTEM');
