name: 'mes_data_quality'
version: '1.0.0'
config-version: 2

profile: 'mes_core'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mes_data_quality:
    +materialized: table
    +schema: dq_results
    staging:
      +materialized: view
    marts:
      +materialized: table

tests:
  mes_data_quality:
    +store_failures: true
    +schema: dq_failures

seeds:
  mes_data_quality:
    +schema: dq_seeds

vars:
  # 数据质量阈值
  accuracy_threshold: 0.95
  completeness_threshold: 0.98
  consistency_threshold: 0.99
  timeliness_threshold: 300  # 5分钟
  validity_threshold: 0.99
  uniqueness_threshold: 1.0
